### PR TITLE
Create .gitignore and added .DS_Store file

### PR DESCRIPTION
**Pull request by gurtatiLND**
The .DS_Store file is a metadata file created by macOS to store custom attributes of a folder. It is automatically created by Finder in each directory accessed and is hidden by default. To prevent .DS_Store files from being tracked, it is good practice to add them to the .gitignore file.

### CODE REVIEW

**Review by CringleySDays — CHANGES_REQUESTED** [review]
Add in a commit where you delete the .DS_Store file please

**Comment by gurtatiLND** [comment]
> Add in a commit where you delete the .DS_Store file please
> 
> (Delete the file from your local and then commit it)

Sorry, I don't get it, what do you @CringleySDays mean?  
My local repo doesn't have such a file(.DS_Store). It is only here in my PR and now in my folder.

**Comment by CringleySDays** [comment]
In your folder meaning in this repo folder or your repo folder (not local one)? 

If it's in your repo folder, then delete the file and commit it, I think it should work that way

**Comment by gurtatiLND** [comment]
@CringleySDays hi, can you please check If I did it right? 
I deleted the file and committed it(I guess).

**Review by CringleySDays — APPROVED** [review]

**Pull request merged**
