### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by khalosmoscato**
videogame + portfolio

### CODE REVIEW

**Review by spargie — APPROVED** [review]
Looking good! :)

**Review by lopezelpesado — CHANGES_REQUESTED** [review]
I'm gunna, hopefully, block this merge and update it to remove the `.DS_Store` files that have snuck in. Not sure how that has happened as they should be ignored 🤔

**Comment by lopezelpesado** [comment]
Oh I see what has happened here! It looks like you forked the repo a while back and have been working off that instead of branching off the repo which is how the `.DS_Store`s have snuck back in!

I'm gunna close this pull request without merging it and ask you to redo the pull request but with a branch off the `summer2024` repo's `main` branch instead of a fork. If you need help with that, I'm around this evening at the meetup.

**Comment by lopezelpesado** [comment]
@spargie, for future reference, you can tell at the top, below the title, that this pull request is requesting pulling code in from another repo (in this case a fork) which you don't usually want to do. The title of the incoming branch has the repo name it's from appended to the branch name before the `:`

image

**Comment by lopezelpesado** [comment]
Actually, I think this might be fine! @khalosmoscato, if you could add a commit getting rid of the `.DS_Store`s then I think it'll be fine to merge this 👍

Let me know if you need help with that!

@spargie, looking a bit more closely at the changes this pull request was proposing I saw that it was just the `.DS_Store` that was the problem (they are there because the repo was forked before the `.gitignore` included those files). Merges from forked repos can be OK but if you notice that the PR is from a fork then maybe it's worth being extra careful with what changes are coming in with it.

**Comment by khalosmoscato** [comment]
Hi @lopezelpesado how do I do that please? I completed my portfolio and video games and wanted to have them uploaded asap, I know the deadline is this Friday 9th of August.

**Review by maxitect — APPROVED** [review]
Right I think the .DS_Store files are deleted now on your forked repo but you need to merge back into the main repo. Hopefully this will work, in general we usually just work off a branch from the main repo and do not need to fork I don't think.

**Comment by khalosmoscato** [comment]
I merged this to the main branch via VScode, by selecting REBASE, and then MAIN. Does it have to be approved now before showing on the main branch under summer2024/users/khalosmoscato?

**Comment by maxitect** [comment]
@khalosmoscato it is not merged, currently it is blocked for merging because Alex requested changes, I believe the changes have now been made so @lopezelpesado will need to confirm and allow merging

**Comment by maxitect** [comment]
Merging generally happens within this github environment once it is approved, there will be a button to merge

**Comment by khalosmoscato** [comment]
Hopefully asap, I already reached CodeWars 6 kyu, so I am ready to finalise my application and submit the website and video game projects before Friday 9th's deadline. @lopezelpesado please let me know when everything is merged and working so that I can submit my projects

**Review by lopezelpesado — APPROVED** [review]
@khalosmoscato I can see that there are still .DS_Store files being added but as they are under your folder I think that won't cause too many problems. Will approve so you can merge this pull request and submit your application!

**Pull request merged**
