### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by RGHANILOO**

### CODE REVIEW

**Review by lopezelpesado — CHANGES_REQUESTED** [review]
Hmm can't seem to get this running on my machine 🤔

**Comment by sofer** [comment]
> Hmm can't seem to get this running on my machine 🤔

That's cos there's nothing in it  🤣

**Review by sofer — APPROVED** [review]
🎉

**Review by lopezelpesado — APPROVED** [review]
Perfect!

**Pull request merged**
